### ISSUE TITLE
Left some console debugging informations

### ISSUE THREAD

**Issue by Deterson** [Thetoto/cestlheure#4]
There are multiple things happening in the log console, especially arrays of rich informations about how things work in the inside.
**_### Never give insight in the inner workings of your application._** You should use a logging service like [LogRocket](https://logrocket.com/) or [Sentry](https://sentry.io/welcome/).

**Comment by TheToto** [comment]
Nobody will see the server side logs, so osef.
But i can make the logs prettier.
