### ISSUE TITLE
Nouvelle stat équipe et autre ptits bonus

### ISSUE THREAD

**Issue by EthanRimo** [Thetoto/cestlheure#7]
Ajouter un bouton "score en équipe" pour le graphique du mois (comme pour le graphique global) afin de voir le nombre de points mis par jour.
Chiant à faire : ajouter un truc de recherche pour voir le classement des horaires spéciaux (miroir : 12H21, 17H01..., suites : 1234, 0123..., GIGATACOS : 19H21 ou encore les sym centrales : 20H05, 22H55...) (ouais c'est ultra casse couilles)

**Comment by TheToto** [comment]
Pour les stats en équipe ouep.
Pour les règles spéciales, on va dire que c'est du long terme (c'est un peu chiant en effet)

**Comment by TheToto** [comment]
Le score en équipe est fait, j'ai mis une ligne "Total par jour" sur la même courbe.
Les horaires spéciaux vont arriver.

Tu peux définir les symétrie centrales, et pourquoi 17h01 est un miroir ?

**Comment by EthanRimo** [comment]
Alors c'est un peu compliqué à expliquer, mais en vrai c'est simple. Une symétrie centrale c'est quand la partie de droite est la partie de gauche retournée. Exemples : 22h55, 15h21, 05h20, 02h50 etc...
En gros tu considères le h comme un point et tu fais une symétrie centrale de la partie de gauche sur ce point.
Et sinon pour 17h01, en fait 17h01 = 16h61 donc miroir (c'est totalement tiré par les cheveux et c'est ce qui fait que les miroirs sont drôles). Pareil pour le gigatacos : 19h21 = 43h21 (donc le miroir de 12h34) mais aussi 19h21 = 18h81 (miroir). C'est pour ça qu'on l'appelle le gigatacos, c'est un horaire double (jsuis parti un peu loin je sais)

**Comment by TheToto** [comment]
Ok pour la symétrie centrale, j'ai compris.

Pour le miroir, ca va pas être plus complexe x). Surtout si on commence a se dire que 19h21 = 43h21 XD
Va falloir trouver un petit algo qui trouve ca avec h et m.

**Comment by TheToto** [comment]
Limite le plus simple c'est de faire une liste exhaustive avec tout les miroirs possible.

**Comment by EthanRimo** [comment]
Allons-y :
00h00
01h10
02h20
03h30
04h40
05h50
07h00 (06h60)
08h10 (07h70)
09h20 (08h80)
10h01
10h30 (09h90)
11h11
12h21
13h31
14h41
15h51
17h01 (16h61)
18h11 (17h71)
19h21 (18h81)
20h02
20h31 (19h91)
21h12
22h22
23h32

**Comment by TheToto** [comment]
Merci, c'est fait.
La symétrie centrale :
https://github.com/Thetoto/cestlheure/blob/master/front/listeners/central_sym.py
Le miroir :
https://github.com/Thetoto/cestlheure/blob/master/front/listeners/miror.py

Il reste plus qu'a adapter le site, mais du coté du bot ca devrais être bon.

**Comment by TheToto** [comment]
Tout est bon maintenant, on peut sélectionner les horaires à afficher.
