### ISSUE TITLE
Le robot ne détecte pas le spam

### ISSUE THREAD

**Issue by Deterson** [Thetoto/cestlheure#8]
On avait à l'époque une règle anti-spam, où une personne qui spammait l'émoji de la conv (ou toute forme de message débile ou sans information) était disqualifié de l'heure. C'était aussi invalidé s'il avait explicitement tenté d'avoir l'heure avant que ça soit l'heure, SAUF si personne d'autre ne réclamait cette heure. BREF.
Il faudrait qu'on en discute, déjà pour
-savoir comment déterminer ce qui est du spam et ce qui n'en est pas, et
-rajouter un système d'arbitrage externe, par exemple si Antoine (notre arbitre) sad react un message ou quoi, ça annule le point... à décider

**Comment by TheToto** [comment]
Tout le monde n'est pas d'accord avec comme appliquer cette règle. Faudrait en discuter (@EthanRimo)
Pour l'emote d'Antoine je crois pas avoir vu de choses permettant de détecter les nouvelles emote avec la lib que j'utilise :/

**Comment by EthanRimo** [comment]
"C'était aussi invalidé s'il avait explicitement tenté d'avoir l'heure avant que ça soit l'heure, SAUF si personne d'autre ne réclamait cette heure."
Pour le coup cette règle est totalement débile pour plusieurs raisons :
- la punition devrait être automatique, dans le sens : si tu envoies un message à 22:21:59, les gens qui auront envoyé un message à 22:22 te l'auront naturellement pris.
- si tu as le temps d'envoyer un autre message (comme par exemple un "oh non :'(" ou un "MISKINA") à la bonne heure, après un échec, c'est que personne d'autre n'était prêt pour le point et que naturellement il doit te revenir
- rater le point en envoyant un message trop tôt enverrait tout simplement une notification à tous les autres membre de la conversation, même s'ils n'avaient pas vu l'heure sacrée. Cela reviendrait donc à potentiellement offrir un point à quelqu'un qui ne le méritait pas

**Comment by Deterson** [comment]
okok d'accord on toz l'idée, à la base c'était pour empêcher le spam **pur** quoi, mais du coup je sais pas comment faire pour mettre des règles de spam plus permissives dans ces cas-là.
Ou alors on laisse tomber et on autorise le spam? parce que si c'est le cas c'est chaud moi je vais turbo spammer hein

**Comment by TheToto** [comment]
> si on envoie entre 19:18:55 et 19:18:59,999, on est lock jusqu'à 19:19:05
je propose de voter sur ce message-même : 
SI VOUS ÊTES D'ACCORD AVEC ÇA, 󰀀
SI VOUS ÊTES PAS D'ACCORD, 👎
SI PLUTOT D'ACCORD, 😮
SI PLUTOT PAS D'ACCORD, 😠

![image](https://user-images.githubusercontent.com/12860648/70864505-02539480-1f53-11ea-957c-466cd93f3c1e.png)

**Comment by TheToto** [comment]
On peut peut être diminuer à 3 secondes, pour que les gens qui ont été ping (et donc ne sont pas trop légitimes) aient pas le temps d'avoir le point

**Comment by TheToto** [comment]
> -rajouter un système d'arbitrage externe, par exemple si Antoine (notre arbitre) sad react un message ou quoi, ça annule le point... à décider

Je suis en train de refaire le bot en Python/Django sur la branche [dev](/Thetoto/cestlheure/tree/dev), ca pourrais être faisable et pas trop compliqué la dessus

**Comment by TheToto** [comment]
wontfix
