### ISSUE TITLE
Idées d'amélioration

### ISSUE THREAD

**Issue by TheToto** [Thetoto/cestlheure#9]
Pour toutes les **petites** idées de nouvelle feature

**Comment by Deterson** [comment]
pas amélioration mais bug: le panel "Participants" est par défaut ouvert et ne veut pas se fermer sur Chrome 😮

**Comment by TheToto** [comment]
@Deterson En fait, c'est plus ou moins voulu, je voulais qu'il soit ouvert par défaut et je pense pas que ça soit réellement utile de vouloir le fermer.
Du coup j'ai forcé l'ouverture sur la version pc car c'était le plus simple

**Comment by Deterson** [comment]
dans le graph du mois en cours, avoir un switch pour passer de la courbe du "cumul total" des jours à la courbe des points PAR jour
